---
title: "Common Syllabi Topics"
output: html_document
bibliography: bibliographies/DSethics-summer2023.bib
link-citations: true
csl: bibliographies/apa-6th-edition.csl
---

----


```{css, echo=FALSE}
h1 {
  text-align: left;
}

.list-group-item.active, .list-group-item.active:focus, .list-group-item.active:hover {
    z-index: 2;
    color: #fff;
    background-color:  #877e2c;
    border-color:  #877e2c;
}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(reactable)
library(reactablefmtr)
```

**METHODOLOGY:**

To determine the syllabi topics, I took the listed course topics, available on [Inside the Syllabi Notes](inside-syllabi.html), and listed them on one document. I then clustered the course topics under more general headings (e.g., I put the  ‘Labor, Automation, and Regulation’ under the heading of ‘Workplace’) to create a more concise list of the syllabi topics.

* Link to [syllabi-topics.csv](https://github.com/scolando/DSethics-summer2023/blob/main/Rmds/syllabi-topics.csv)

----

# Syllabi Topics

----

```{r message=FALSE, warning=FALSE, fig.alt = "This is a table of the syllabi topics ordered from most common to least common. There are two columns: 'Syllabi Topic' and 'Count'. 'Count' represents the number of times the syllabi topic came up in the collected syllabi. The most common topic is 'Privacy' with a count of 11. 'Privacy' is followed by 'Bias' and 'Justice', both of which a count of 8.", fig.align='center', fig.cap="Syllabi Topics, arranged in Descending Order by Count"}
syllabi_topics <- readr::read_csv("syllabi-topics.csv")

syllabi_topics %>%
  group_by(Syllabi_Topics) %>%
  count() %>%
  arrange(desc(n)) %>%
  rename(Count = n) %>%
  reactable(
    columns = list(Syllabi_Topics = colDef("Syllabi Topic"),
    Count = colDef("Count")),
    highlight = TRUE,
    showSortable = TRUE,
    showPagination = TRUE,
    searchable = TRUE,
    defaultPageSize = 8,
    width = '100%',
    theme = reactableTheme(
             highlightColor = "#F0EDD1",
             style = list(
      fontFamily = "-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif"
             )))
```

----

# Most Common Syllabi Topics

----

<span style="color:#877e2c; background-color: #F0EDD1; border: 3px solid #F0EDD1; border-radius: 4px;">**'Most Common' = has a count of 3 or more**</span>
<br>

```{r message=FALSE, warning=FALSE, fig.align='center', fig.alt = "This is a table of the most common syllabi topics ordered from most common to least common. There are two columns: 'Syllabi Topic' and 'Count'. 'Count' represents the number of times the syllabi topic came up in the collected syllabi. Only syllabi topics with a count greater or equal to 3 are in the table. The most common topic is 'Privacy' with a count of 11. 'Privacy' is followed by 'Bias' and 'Justice', both of which a count of 8.", fig.cap="Most Common Syllabi Topics, arranged in Descending Order by Count"}
syllabi_topics <- readr::read_csv("syllabi-topics.csv")

syllabi_topics %>%
  group_by(Syllabi_Topics) %>%
  count() %>%
  arrange(desc(n)) %>%
  rename(Count = n) %>%
  filter(Count >= 3) %>% 
  reactable(
    columns = list(Syllabi_Topics = colDef("Syllabi Topic"),
    Count = colDef("Count")),
    highlight = TRUE,
    showSortable = TRUE,
    pagination = FALSE,
    searchable = TRUE,
    width = '100%',
    theme = reactableTheme(
             highlightColor = "#F0EDD1",
             style = list(
      fontFamily = "-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif"
             ))) 
```
